### ISSUE TITLE
Resolutions in Ubi.ini must be specific

### ISSUE THREAD

**Issue by RibShark** [spitfirex86/Ray2Fix#1]
Right now, selecting a resolution from the list will set the same resolution in ubi.ini. However, Glide is limited to a strict set of resolutions, and setting it otherwise will cause the window to remain white.

The allowed resolutions are 320x200, 400x300, 512x384, 640x480, 800x600, 1024x768, 1280x1024, 1600x1200.

Obviously the dgVoodoo resolution can be set to whatever and it will output. I would check the width of the set resolution the ubi.ini resolution to the smallest one that is larger than that width (except maybe 1600x1200 as the loading bars look a little weird with that).

**Comment by spitfirex86** [comment]
Fixed in 00b87e1f96ef8e1f2b04cab7b5ea0096b6f5c43f .
