### ISSUE TITLE
How do i remove the watermark?

### ISSUE THREAD

**Issue by LethalManBoob** [spitfirex86/Ray2Fix#5]
title

**Comment by XanderNT** [comment]
You dont, its there to prevent from speedrunning cheating

**Comment by LethalManBoob** [comment]
> You dont, its there to prevent from speedrunning cheating

Well beyond being the sillyest thing ever. It prevents me from using it to... yknow.. PLAY IT!

**Comment by spitfirex86** [comment]
Disable mods in Ray2Fix settings.

Mods enabled == watermark ON

Mods disabled == watermark OFF
