### ISSUE TITLE
Missing .dll file issue

### ISSUE THREAD

**Issue by Eotena** [spitfirex86/Ray2Fix#8]
![image](https://github.com/spitfirex86/Ray2Fix/assets/33289650/2a96ee07-af99-4df1-9c70-cac6abbd21a1)
After recently installing rayman 2 via GoG galaxy, I can't get ray2fix to work on windows 10 as it complains about a missing .dll file, even when reinstalling the game. Is there a solution for this issue? I checked manually, and the file in question does exist in the DLL folder of thee game.

**Comment by alphadijkstra** [comment]
Was it ``GliVd1vf.dll`` ? Had the same issue. Started working when I copied it from the Rayman 2 -> DLL -> Glide folder to the DLL folder.

**Comment by spitfirex86** [comment]
Yes, this is the solution.

Usually this is specific to the old version of the GOG standalone installer, which places the DLL in the wrong directory (this tends to be an issue for people using *backups* of the installer...)

Weird that the Galaxy client would do the same. Either way, my recommendation is to always use the latest version of the manual installer.
